server:
  port: 8080
  
spring:
   datasource:
      driver-class-name: org.hsqldb.jdbc.JDBCDriver
      jdbc-url: jdbc:hsqldb:hsql://localhost/survey
      username: sa
      password:
   jpa:
      hibernate:
         ddl-auto: update
