server:
  port: 8081

spring:
   datasource:
      driver-class-name: org.hsqldb.jdbc.JDBCDriver
      jdbc-url: jdbc:hsqldb:hsql://localhost/survey
      username: sa
      password:
      initialization-mode: never
   jpa:
      hibernate:
        ddl-auto: none